apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-client
  template:
    metadata:
      labels:
        app: user-client
    spec:
      containers:
        - name: capstone-fe
          image: docker.io/doanhthuc/capstone-fe:latest
          ports:
            - containerPort: 5173

---
apiVersion: v1
kind: Service
metadata: 
  name: client-service
es.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec: 
  selector:
    app: user-client
  ports:
    - name: port-1
      protocol: TCP
      port: 5173
      targetPort: 5173
  type: LoadBalancer